### ISSUE TITLE
authentication_strategy_doordash throwing mypy error

### ISSUE THREAD

**Issue by sanders41** [ethyca/fides#1471]
### Bug Description

mypy is currently throwing a mypy error on `authentication_strategy_doordash.py`

```console
src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_doordash.py:50: error: Argument 2 to "assign_placeholders" has
incompatible type "Optional[Any]"; expected "Dict[str, Any]"  [arg-type]
                    "iss": assign_placeholders(self.developer_id, secrets),
                                                                  ^~~~~~~
src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_doordash.py:51: error: Argument 2 to "assign_placeholders" has
incompatible type "Optional[Any]"; expected "Dict[str, Any]"  [arg-type]
                    "kid": assign_placeholders(self.key_id, secrets),
```

#### Steps to Reproduce

1. Pull the latest main
1. Run mypy

### Expected behavior

No errors.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

The PR that added the door dash authentication strategy and a PR to update mypy both landed at about the same time, and because of this the doordash code passed the original mypy, but is failing with the new settings.
