### PR TITLE
Fix evaluations page after evaluation model refactor

### LINKED ISSUE #300: Evaluations page returns Internal Server Error after Evaluation refactoring
### Bug Description

Evaluations page does not work at the moment

#### Steps to Reproduce

1. Go to http://0.0.0.0:8080/view/evaluations

### Expected behavior

Evaluations should show up here

### Additional context

Broken by #286

### PR DESCRIPTION
**Pull request by earmenda**
Closes #300

### Code Changes

* [x] Fixed usages of old details attribute in evaluation model

### Steps to Confirm

* [x] Verified view in http://0.0.0.0:8080/view/evaluations

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* [x] Documentation Updated

### Description Of Changes

my b

### CODE REVIEW

**Comment by earmenda** [comment]
Fixes this error:
```fides-fidesctl-1  | 'Evaluation' object has no attribute 'details```

**Comment by earmenda** [comment]
@ThomasLaPiana 

This should be easy to merge. Is this something that mypy should have caught? A simple integration test woulda caught this also.

**Comment by earmenda** [comment]
One todo which I would like to add from this is showing this exception in our server logs. I've ran into this before when the api raises some uncaught exception but is lost. Need to do a little research on this, but opening an issue makes sense.

**Review by ThomasLaPiana — APPROVED** [review]
tested locally, works for me!
