### PR TITLE
Fix mypy error

### LINKED ISSUE #1471: authentication_strategy_doordash throwing mypy error
### Bug Description

mypy is currently throwing a mypy error on `authentication_strategy_doordash.py`

```console
src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_doordash.py:50: error: Argument 2 to "assign_placeholders" has
incompatible type "Optional[Any]"; expected "Dict[str, Any]"  [arg-type]
                    "iss": assign_placeholders(self.developer_id, secrets),
                                                                  ^~~~~~~
src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_doordash.py:51: error: Argument 2 to "assign_placeholders" has
incompatible type "Optional[Any]"; expected "Dict[str, Any]"  [arg-type]
                    "kid": assign_placeholders(self.key_id, secrets),
```

#### Steps to Reproduce

1. Pull the latest main
1. Run mypy

### Expected behavior

No errors.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

The PR that added the door dash authentication strategy and a PR to update mypy both landed at about the same time, and because of this the doordash code passed the original mypy, but is failing with the new settings.

### PR DESCRIPTION
**Pull request by sanders41**
Closes #1471

### Code Changes

* [x] Properly handle types in `authentication_strategy_doordash.py`

### Steps to Confirm

* [x] Run mypy

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

There are a couple other open PRs that contain this fix, but they are unrelated to this issue and only contain the fix to resolve the mypy error. Because they are for different topics they could take longer to get reviewed and merged so I am opening this PR to fix the error quicker.

### CODE REVIEW

**Review by adamsachs — APPROVED** [review]
this should be fine (i.e. it's just as good as what was there and will satisfy the type checker), though i do wonder whether we should throw an explicit error with a clear message if `secrets` is `None` and `add_authentication` has been called, since i _think_ it's a possible code path and i _think_ it'd be indicative of a user error?

@galvana what do you think? ~also noting that @galvana was fixing this up in his pending PR [here](https://github.com/ethyca/fides/pull/1441/files#diff-a6f1ad901d25f05244510fece14d54f8b688311ef2d420cf49956be808322e97), but i'd prefer  to handle the optional as you've done here than to ignore the type checker.~ i see now your note in the PR about getting this merged quickly - i'm all for that. if a clearer error message is indeed appropriate here, perhaps @galvana can add that on his pending PR, since it would fall in the realm of cleaning up saas inconsistencies.

either way, i'm approving, since i don't want to hold this up, i'm nitpicking a bit here!
